### ISSUE TITLE
Organização - Brainstorming Magalu

### ISSUE THREAD

**Issue by brunna-martins** [UnBArqDsw2023-2/2023.2_G8_ProjetoMagazineLuiza#15]
### Descrição

A primeira fase de uma Design Sprint consiste em entender o projeto no qual se está trabalhando. Para isso, decidimos fazer uma sessão assíncrona de Brainstorming para reunir ideias de quais serão os focos desse projeto. Depois disso, três membros do grupo foram selecionados para escolher quais ideias são pertinentes e quais serão descartadas; após esse processo, será repassado ao time inteiro que ideias serão continuadas para que cada membro valide a decisão.

### Tarefas

- [x] Cada membro colocou ideias no arquivo Miro da equipe
- [x] @iagoscm @MauricioMachadoFF @Neitan2001 selecionaram as ideias mais pertinentes
- [x] Grupo validou as ideias que serão levadas adiante

### Prazo

**08/09/2023, 23h59.**

### Código de Conduta

- [X] Concordo em seguir o Código de Conduta.

**Comment by iagoscm** [comment]
Issue finalizada em reunião no dia 10/09/2023. 
Encaminhamentos:
- Validar priorização com o grupo em aula
- Definir quarto artefato (Plano de riscos)
- Criar e delegar issues para as duplas
- Entender fase de prototipação com a professora
