### ISSUE TITLE
Mapa Mental: criação e validação do artefato

### ISSUE THREAD

**Issue by MauricioMachadoFF** [UnBArqDsw2023-2/2023.2_G8_ProjetoMagazineLuiza#18]
### Descrição

Criar artefato Mapa Mental para projeto Magazineluiza

### Tarefas

# Critérios para estar pronto

- [x] Artefato criado e inserido na documentação do projeto
- [x] Em caso de versionamento do artefato, mostrar múltiplas versões do arquivo

# Critérios para ser aceito

- Revisado e aprovado por uma pessoa
- Ter todos os comentários do PR resolvidos

### Prazo

Data de entrega 12/09/2023

### Código de Conduta

- [X] Concordo em seguir o Código de Conduta.

**Comment by iagoscm** [comment]
Página de Mapa mental do fluxo do Magazine Luiza foi adicionado diretamente na branch de Design Sprint, estando relacionado à documentação na issue #21
