### ISSUE TITLE
Documentação da Design Sprint

### ISSUE THREAD

**Issue by MauricioMachadoFF** [UnBArqDsw2023-2/2023.2_G8_ProjetoMagazineLuiza#21]
### Descrição

Documentar etapas do Design Sprint

### Tarefas

# Critérios para estar pronto

- [x] Documentar fase 1 (unpack): 
  - [x] documentar brainstorm de metodologias  (pedir fotos das etapas para @MauricioMachadoFF)
  - [x] documentar mapa mental das metodologias (parte de metodologias deve ter um arquivo exclusivo para ele)
  - [x] documentar brainstorm do projeto (segundo brainstorm realizado no miro, pedir fotos para @Neitan2001 e @iagoscm)

- [x] Documentar fase 2 (sketch)
  - [x] Documentar todos os artefatos (demais issues devem estar completas para seguir)

- [x] Documentar fase 3 (decision)
  - [x] Documentar versão final dos artefatos pós-validação da equipe

- [x] Documentar fase 4 (prototype)
  - [x] Definir o que fazer aqui (aguardando professora)

# Critérios para ser aceito

- Revisado e aprovado por uma pessoa
- Ter todos os comentários do PR resolvidos

### Código de Conduta

- [X] Concordo em seguir o Código de Conduta.

**Comment by brunna-martins** [comment]
Primeira versão do artefato colocada na branch referente à issue.

**Comment by iagoscm** [comment]
Unpack finalizado, páginas de brainstorm e mapa mental feitas, atualizadas na design sprint
Sidebar atualizada (pode dar problemas de merge, verificar com atenção depois)

**Comment by brunna-martins** [comment]
Fase de Sketch colocada, faltam somente os artefatos de BPMN para finalizá-la.

**Comment by brunna-martins** [comment]
Há correções a serem feitas no artefato, é preciso discutir sobre a fase final (se será entregue a tempo) e é preciso colocar o protótipo.

**Comment by brunna-martins** [comment]
A primeira entrega da disciplina de Arquitetura e Desenho de Software ocorreu no dia 15/09/2023. O artefato de Design Sprint foi concluído nesse dia. A apresentação em sala de nosso grupo ficou marcada para dia 18/09/2023.
